/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated.profil'
import { Route as AuthenticatedPenggunaRouteImport } from './routes/_authenticated.pengguna'
import { Route as AuthenticatedPengaturanRouteImport } from './routes/_authenticated.pengaturan'
import { Route as AuthenticatedPelangganRouteImport } from './routes/_authenticated.pelanggan'
import { Route as AuthenticatedKwitansiRouteImport } from './routes/_authenticated.kwitansi'
import { Route as AuthenticatedInvoiceRouteImport } from './routes/_authenticated.invoice'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedArsipRouteImport } from './routes/_authenticated.arsip'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPenggunaRoute = AuthenticatedPenggunaRouteImport.update({
  id: '/pengguna',
  path: '/pengguna',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPengaturanRoute = AuthenticatedPengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPelangganRoute = AuthenticatedPelangganRouteImport.update({
  id: '/pelanggan',
  path: '/pelanggan',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKwitansiRoute = AuthenticatedKwitansiRouteImport.update({
  id: '/kwitansi',
  path: '/kwitansi',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInvoiceRoute = AuthenticatedInvoiceRouteImport.update({
  id: '/invoice',
  path: '/invoice',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedArsipRoute = AuthenticatedArsipRouteImport.update({
  id: '/arsip',
  path: '/arsip',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/arsip': typeof AuthenticatedArsipRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/invoice': typeof AuthenticatedInvoiceRoute
  '/kwitansi': typeof AuthenticatedKwitansiRoute
  '/pelanggan': typeof AuthenticatedPelangganRoute
  '/pengaturan': typeof AuthenticatedPengaturanRoute
  '/pengguna': typeof AuthenticatedPenggunaRoute
  '/profil': typeof AuthenticatedProfilRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/arsip': typeof AuthenticatedArsipRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/invoice': typeof AuthenticatedInvoiceRoute
  '/kwitansi': typeof AuthenticatedKwitansiRoute
  '/pelanggan': typeof AuthenticatedPelangganRoute
  '/pengaturan': typeof AuthenticatedPengaturanRoute
  '/pengguna': typeof AuthenticatedPenggunaRoute
  '/profil': typeof AuthenticatedProfilRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/arsip': typeof AuthenticatedArsipRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/invoice': typeof AuthenticatedInvoiceRoute
  '/_authenticated/kwitansi': typeof AuthenticatedKwitansiRoute
  '/_authenticated/pelanggan': typeof AuthenticatedPelangganRoute
  '/_authenticated/pengaturan': typeof AuthenticatedPengaturanRoute
  '/_authenticated/pengguna': typeof AuthenticatedPenggunaRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/arsip'
    | '/dashboard'
    | '/invoice'
    | '/kwitansi'
    | '/pelanggan'
    | '/pengaturan'
    | '/pengguna'
    | '/profil'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/arsip'
    | '/dashboard'
    | '/invoice'
    | '/kwitansi'
    | '/pelanggan'
    | '/pengaturan'
    | '/pengguna'
    | '/profil'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/arsip'
    | '/_authenticated/dashboard'
    | '/_authenticated/invoice'
    | '/_authenticated/kwitansi'
    | '/_authenticated/pelanggan'
    | '/_authenticated/pengaturan'
    | '/_authenticated/pengguna'
    | '/_authenticated/profil'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pengguna': {
      id: '/_authenticated/pengguna'
      path: '/pengguna'
      fullPath: '/pengguna'
      preLoaderRoute: typeof AuthenticatedPenggunaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pengaturan': {
      id: '/_authenticated/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof AuthenticatedPengaturanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pelanggan': {
      id: '/_authenticated/pelanggan'
      path: '/pelanggan'
      fullPath: '/pelanggan'
      preLoaderRoute: typeof AuthenticatedPelangganRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kwitansi': {
      id: '/_authenticated/kwitansi'
      path: '/kwitansi'
      fullPath: '/kwitansi'
      preLoaderRoute: typeof AuthenticatedKwitansiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoice': {
      id: '/_authenticated/invoice'
      path: '/invoice'
      fullPath: '/invoice'
      preLoaderRoute: typeof AuthenticatedInvoiceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/arsip': {
      id: '/_authenticated/arsip'
      path: '/arsip'
      fullPath: '/arsip'
      preLoaderRoute: typeof AuthenticatedArsipRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedArsipRoute: typeof AuthenticatedArsipRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInvoiceRoute: typeof AuthenticatedInvoiceRoute
  AuthenticatedKwitansiRoute: typeof AuthenticatedKwitansiRoute
  AuthenticatedPelangganRoute: typeof AuthenticatedPelangganRoute
  AuthenticatedPengaturanRoute: typeof AuthenticatedPengaturanRoute
  AuthenticatedPenggunaRoute: typeof AuthenticatedPenggunaRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedArsipRoute: AuthenticatedArsipRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInvoiceRoute: AuthenticatedInvoiceRoute,
  AuthenticatedKwitansiRoute: AuthenticatedKwitansiRoute,
  AuthenticatedPelangganRoute: AuthenticatedPelangganRoute,
  AuthenticatedPengaturanRoute: AuthenticatedPengaturanRoute,
  AuthenticatedPenggunaRoute: AuthenticatedPenggunaRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
